return {
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	main = "nvim-treesitter.configs",
	opts = {
		-- https://github.com/nvim-treesitter/nvim-treesitter/blob/main/SUPPORTED_LANGUAGES.md
		ensure_installed = {
			"arduino",
			"bibtex",
			"bitbake",
			"bash",
			"c",
			"cmake",
			"cpp",
			"css",
			"csv",
			"html",
			"json",
			"jq",
			"kconfig",
			-- "latex", -- throws warnings
			"lua",
			"markdown",
			"markdown_inline",
			"nginx",
			"objdump",
			"powershell",
			"python",
			"regex",
			"toml",
			"typst",
			"udev",
			"vim",
			"vimdoc",
			"yaml",
			"zig",
			-- "zsh", -- not installable
		},
		highlight = { enable = true },
		indent = { enable = true },
	},
}
