PROMPT_COMMAND='PS1_CMD1=$(git branch --show-current 2>/dev/null || echo "null")'; PS1='\[\e[38;5;45m\][\[\e[38;5;207m\]${PS1_CMD1}\[\e[38;5;45m\]]\[\e[0m\] \[\e[38;5;82m\]\W\[\e[0m\] \[\e[38;5;226m\]\$\[\e[0m\] '
alias vim=nvim
alias ls="ls --color"
set -o vi
